#!/usr/bin/env python3

import sys,os, time

if __name__ == '__main__':
    if (len(sys.argv) < 2):
        print('Usage: python3 scan_start_stat.py $test_result')
        print('$test_result is generated by kschedule type 13 event')
        exit()

    output_array = [0 for i in range(512)]
    index = 0

    with open(sys.argv[1], 'r') as ifile:
        for line in ifile:
            line = line.strip()
            temp_list = line.split(",")
            if (len(temp_list) > 2):
                try:
                    start_token = temp_list[2].replace("start:", "").replace(" ", "")
                    output_array[int(start_token)] += 1
                except Exception:
                    print("Found error text:")
                    print(temp_list[2])
                    break

    # print(",".join(output_array))
    for i in range(len(output_array)):
        print("{index}:{value}".format(index=i, value=output_array[i]))
